# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Thinkport < Formula
  desc "This cli tool provides a set of commands related to Thinkport. This is a technical experiement and not intended for production use."
  homepage "https://github.com/vergissberlin/thinkport"
  version "0.0.73"
  license "MIT"
  depends_on :linux

  on_arm do
    if Hardware::CPU.is_64_bit?
      url "https://github.com/vergissberlin/thinkport/releases/download/0.0.73/thinkport_linux_arm64.tar.gz"
      sha256 "661098935a504016738559327438a47b5ab435b5cbd3fa67a2789c151e8c2170"

      def install
        bin.install "thinkport"
      end
    end
  end

  def caveats
    <<~EOS
      It uses a http client to collect the data. Internet connection is required.
    EOS
  end

  test do
    system "#{bin}/thinkport", "--version"
  end
end
