# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Thinkport < Formula
  desc "This cli tool provides a set of commands related to Thinkport. This is a technical experiement and not intended for production use."
  homepage "https://github.com/vergissberlin/thinkport"
  version "0.0.71"
  license "MIT"
  depends_on :linux

  on_arm do
    if Hardware::CPU.is_64_bit?
      url "https://github.com/vergissberlin/thinkport/releases/download/0.0.71/thinkport_linux_arm64.tar.gz"
      sha256 "4967262e6292c0868fecf3eccfd1a879c4eb7c3c7819b0ccc9fd75bd1dae0236"

      def install
        bin.install "thinkport"
      end
    end
  end

  def caveats
    <<~EOS
      It uses a http client to collect the data. Internet connection is required.
    EOS
  end

  test do
    system "#{bin}/thinkport", "--version"
  end
end
