# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Thinkport < Formula
  desc "This cli tool provides a set of commands related to Thinkport. This is a technical experiement and not intended for production use."
  homepage "https://github.com/vergissberlin/thinkport"
  version "0.0.55"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vergissberlin/thinkport/releases/download/0.0.55/thinkport_Darwin_x86_64.tar.gz"
      sha256 "60841bc0220e31018a4a91e9c7a2783c6d35054cf02c18786f3c19f651ec6d59"

      def install
        bin.install "thinkport"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vergissberlin/thinkport/releases/download/0.0.55/thinkport_Darwin_arm64.tar.gz"
      sha256 "31e002e09789f5c1b199c9ac42d763199feb8f41994e3b67622b07368ceae952"

      def install
        bin.install "thinkport"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vergissberlin/thinkport/releases/download/0.0.55/thinkport_Linux_arm64.tar.gz"
      sha256 "260ca2f28475f5688989ef1127161c7731d9150fb2c0c3cc2e9621820017dc83"

      def install
        bin.install "thinkport"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vergissberlin/thinkport/releases/download/0.0.55/thinkport_Linux_x86_64.tar.gz"
      sha256 "9bd9f9bff6cc8459dd49d1e28df079ef8c7b804e9fbcf433f4f13e5506529fc6"

      def install
        bin.install "thinkport"
      end
    end
  end

  def caveats
    <<~EOS
      It uses a http client to collect the data. Internetconnection is required.
    EOS
  end

  test do
    system "#{bin}/thinkport -v"
  end
end
